megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }

check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]

post_request_icon:
    pattern: /request/{requestId}/icon
    defaults: { _controller: MegasoftEntangleBundle:Request:postIcon }
    methods: [POST]
    requirements:
        requestId:  \d+