megasoft_entangle_homepage:
    pattern:  /hello/{hello}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }
    methods: [GET]
    
filter_requests_in_tangle:
    pattern:  /tangle/{tangleId}/request
    defaults: { _controller: MegasoftEntangleBundle:Tangle:filterRequests }
    methods: [GET]
    requirements:
        tangleId:  \d+

fetch_tags_in_tangle:
    pattern:  /tangle/{tangleId}/tag
    defaults: { _controller: MegasoftEntangleBundle:Tangle:allTags}
    methods: [GET]
    requirements:
        tangleId:  \d+
        
check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]

_register:
  pattern: /register
  defaults: {_controller: MegasoftEntangleBundle:Notification:register }
  requirements:
          _method:  POST|GET


_test:
  pattern: /test
  defaults: {_controller: MegasoftEntangleBundle:Notification:test}
  methods: [GET]