megasoft_entangle_homepage:
    pattern:  /hello/{hello}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }
    methods: [GET]
    
filter_requests_in_tangle:
    pattern:  /tangle/{tangleId}/request
    defaults: { _controller: MegasoftEntangleBundle:Tangle:filterRequests }
    methods: [GET]
    requirements:
        tangleId:  \d+

fetch_tags_in_tangle:
    pattern:  /tangle/{tangleId}/tag
    defaults: { _controller: MegasoftEntangleBundle:Tangle:allTags}
    methods: [GET]
    requirements:
        tangleId:  \d+
        
check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]


login:
    pattern:  /user/login
    defaults: { _controller: MegasoftEntangleBundle:User:login}
    methods: [POST]
    
    
acceptOffer:
    pattern: /accept/offer
    defaults: {_controller: MegasoftEntangleBundle:Offer:acceptOffer }
    methods: [POST]

dummy:
    pattern: /dummy
    defaults: { _controller: MegasoftEntangleBundle:Default:dummy }


get_profile:
    pattern: tangle/{tangleId}/user/{userId}/profile
    defaults: { _controller: MegasoftEntangleBundle:User:profile }
    methods: [GET]
