megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }

#megasoft_entangle_test:
#    pattern:  /test
#    defaults: { _controller: MegasoftEntangleBundle:Default:test }

check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]
    
check_availability:
    pattern: /tangle/check
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkAvailability }
    methods: [GET]

create_tangle:
    pattern: /tangle
    defaults: { _controller: MegasoftEntangleBundle:Tangle:createTangle }
    methods: [POST]

