megasoft_entangle_homepage:
    pattern:  /hello/{hello}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }
    methods: [GET]
    
filter_requests_in_tangle:
    pattern:  /tangle/{tangleId}/request
    defaults: { _controller: MegasoftEntangleBundle:Tangle:filterRequests }
    methods: [GET]
    requirements:
        tangleId:  \d+

fetch_tags_in_tangle:
    pattern:  /tangle/{tangleId}/tag
    defaults: { _controller: MegasoftEntangleBundle:Tangle:allTags}
    methods: [GET]
    requirements:
        tangleId:  \d+
        
check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]
    
check_availability:
    pattern: /tangle/check
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkAvailability }
    methods: [GET]

create_tangle:
    pattern: /tangle
    defaults: { _controller: MegasoftEntangleBundle:Tangle:createTangle }
    methods: [POST]
    
index:
    pattern: /
    defaults: { _controller: MegasoftEntangleBundle:Site:index }
    
fetch_pending_invitations:
    pattern: /tangle/{tangleId}/pending-invitations
    defaults: { _controller: MegasoftEntangleBundle:Tangle:pendingInvitations}
    methods: [GET]

accept_pending_invitation:
    pattern: /pending-invitation/{pendingInvitationId}/accept
    defaults: { _controller: MegasoftEntangleBundle:Tangle:acceptPendingInvitation}
    methods: [PUT]

reject_pending_invitation:
    pattern: /pending-invitation/{pendingInvitationId}/reject
    defaults: { _controller: MegasoftEntangleBundle:Tangle:rejectPendingInvitation}
    methods: [DELETE]


accept_tangle_invitation:
    pattern: /tangle-invitation/{tangleId}/{userId}/accept
    defaults: { _controller: MegasoftEntangleBundle:Tangle:addUser}
    methods: [PUT]

viewRequest:
    pattern: tangle/{tangleId}/request/{requestId}
    defaults: { _controller: MegasoftEntangleBundle:Request:viewRequest }
    methods: [GET]


create:
    pattern: /tangle/{tangleId}/request
    defaults: { _controller: MegasoftEntangleBundle:Request:create }
    methods: [POST]
    

acceptOffer:
    pattern: /accept/offer
    defaults: {_controller: MegasoftEntangleBundle:Offer:acceptOffer }
    methods: [POST]

dummy:
    pattern: /dummy
    defaults: { _controller: MegasoftEntangleBundle:Default:dummy }


verification:
    pattern: /verify/{verificationCode}
    defaults: { _controller:MegasoftEntangleBundle:Verification:verifyUser}


create_Offer:
    pattern: /tangle/{tangleId}/request/{requestId}/offer
    defaults: { _controller: MegasoftEntangleBundle:CreateOffer:createOffer }
    methods: [POST]

get_profile:
    pattern: /tangle/{tangleId}/user/{userId}/profile
    defaults: { _controller: MegasoftEntangleBundle:User:profile }
    methods: [GET]
    
get_tangles:
    pattern: /tangle
    defaults: { _controller: MegasoftEntangleBundle:Tangle:getTangles }
    methods: [GET]


get_offer:
    pattern: /offer/{offerId}
    defaults: { _controller: MegasoftEntangleBundle:Offer:offer }


