megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }
#megasoft_entangle_test:
#    pattern:  /test
#    defaults: { _controller: MegasoftEntangleBundle:Default:test }

Verification:
    pattern:  /verify/{verificationCode}
    defaults: { _controller: MegasoftEntangleBundle:Verification:verifyUser}
emailing:      #this is for testing purposes only 
    pattern:  /email/{userEmail}/{userName}/{verificationHash}
    defaults: { _controller: MegasoftEntangleBundle:Verification:emailUser}  
    
check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]

