megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }

#megasoft_entangle_test:
#    pattern:  /test
#    defaults: { _controller: MegasoftEntangleBundle:Default:test }

getRequestDetails:
    pattern: /Request/{requestId}
    defaults: { _controller: MegasoftEntangleBundle:ShowRequest:getRequestDetails }
    methods: [GET]

