megasoft_entangle_homepage:
    pattern:  /hello/{hello}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }
    methods: [GET]
    
filter_requests_in_tangle:
    pattern:  /tangle/{tangleId}/request
    defaults: { _controller: MegasoftEntangleBundle:Tangle:filterRequests }
    methods: [GET]
    requirements:
        tangleId:  \d+


fetch_tags_in_tangle:
    pattern:  /tangle/{tangleId}/tag
    defaults: { _controller: MegasoftEntangleBundle:Tangle:allTags}
    methods: [GET]
    requirements:
        tangleId:  \d+
        
check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]
    
login:
    pattern:  /login
    defaults: { _controller: MegasoftEntangleBundle:User:login}
    methods: [POST]
    
whoami: 
    pattern:  /whoami
    defaults: { _controller: MegasoftEntangleBundle:User:whoAmI}
    methods: [GET]
    
check_availability:
    pattern: /tangle/check
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkAvailability }
    methods: [GET]


create_tangle:
    pattern: /tangle
    defaults: { _controller: MegasoftEntangleBundle:Tangle:createTangle }
    methods: [POST]

create:
    pattern: /tangle/{tangleId}/request
    defaults: { _controller: MegasoftEntangleBundle:Request:create }
    methods: [POST]
   
tangles:
    pattern: /tangle
    defaults: { _controller: MegasoftEntangleBundle:Tangle:get }
    methods: [GET]
    
create_Offer:
    pattern: /tangle/{tangleId}/request/{requestId}/offer
    defaults: { _controller: MegasoftEntangleBundle:CreateOffer:createOffer }
    methods: [POST]

get_profile:
    pattern: tangle/{tangleId}/user/{userId}/profile
    defaults: { _controller: MegasoftEntangleBundle:User:getProfile }
    methods: [GET]
    
index:
    pattern: /
    defaults: { _controller: MegasoftEntangleBundle:Site:index }

megasoft_entangle_register:
    pattern:  /register
    defaults: { _controller: MegasoftEntangleBundle:Register:register }

about:
    pattern:  /about
    defaults: { _controller: MegasoftEntangleBundle:About:about }
    
viewRequest:
    pattern: /request/{requestId}
    defaults: { _controller: MegasoftEntangleBundle:Request:viewRequest }
    methods: [GET]

dummy:
    pattern: /dummy
    defaults: { _controller: MegasoftEntangleBundle:Default:dummy }
