megasoft_entangle_homepage:
    pattern:  /hello/{hello}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }
    methods: [GET]
    
filter_requests_in_tangle:
    pattern:  /tangle/{tangleId}/request
    defaults: { _controller: MegasoftEntangleBundle:Tangle:filterRequests }
    methods: [GET]
    requirements:
        tangleId:  \d+

fetch_tags_in_tangle:
    pattern:  /tangle/{tangleId}/tag
    defaults: { _controller: MegasoftEntangleBundle:Tangle:allTags}
    methods: [GET]
    requirements:
        tangleId:  \d+
        
check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]

dummy:
    pattern: /dummy
    defaults: { _controller: MegasoftEntangleBundle:Default:dummy }

create_unfreeze_request:
    pattern: /unfreze
    defaults: { _controller: MegasoftEntangleBundle:Unfreeze:createRequest }
    methods: [POST]

retrieve_unfreeze_requests:
    pattern: /unfreze
    defaults: { _controller: MegasoftEntangleBundle:Unfreeze:getUnfreezeReq }
    methods: [GET]

delete_unfreeze_requests:
    pattern: /unfreeze/{unfreezeReqid}
    defaults: { _controller: MegasoftEntangleBundle:Unfreeze:removeRequest }
    methods: [DELETE]

get_unfreeze_request:
    pattern: /unfreeze/{unfreezeReqid}
    defaults: { _controller: MegasoftEntangleBundle:Unfreeze:getRequest }
    methods: [GET]

get_frozen_points:
    pattern: /unfreeze/{unfreezeReqid}/frozenpoints
    defaults: { _controller: MegasoftEntangleBundle:Unfreeze:getFP }
    methods: [GET]

restore_balance:
    pattern: /unfreeze/{unfreezeReqid}/frozenpoints
    defaults: { _controller: MegasoftEntangleBundle:Unfreeze:restoreFP }
    methods: [PUT]