megasoft_entangle_homepage:
    pattern:  /tangle/{tangleId}/request?userid={userId}&tagid={tagId}&fulltext={fullText}&usernameprefix={usernamePrefix}
    defaults: { _controller: MegasoftEntangleBundle:Tangle:filterRequests }
    methods: [GET]
    
    pattern: /tangle/{tangleId}/tag
    defaults: { _controller: MegasoftEntangleBundle:Tangle:allTags}
    methods: [GET]