megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }

fetch_users_in_tangle:
    pattern:  /tangle/{tangleId}/user
    defaults: { _controller: MegasoftEntangleBundle:Default:allusers }
    methods: [GET]
