megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }

#megasoft_entangle_test:
#    pattern:  /test
#    defaults: { _controller: MegasoftEntangleBundle:Default:test }

getRequestAttibutes:
    pattern: /request/{requestId}
    defaults: { _controller: MegasoftEntangleBundle:ShowRequest:getRequestAttibutes }
    methods: [GET]

