megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }
megasoft_entangle_verificationpage:
    pattern: /verify/{verificationHash}
    defaults : {_controller: MegasoftEntangleBundle:Verification:verifyUser}
#megasoft_entangle_test:
#    pattern:  /test
#    defaults: { _controller: MegasoftEntangleBundle:Default:test }
