megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }

#megasoft_entangle_test:
#    pattern:  /test
#    defaults: { _controller: MegasoftEntangleBundle:Default:test }

check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]
    
fetch_pending_invitations:
    pattern: /tangle/{tangleId}/pending-invitations
    defaults: { _controller: MegasoftEntangleBundle:Tangle:pendingInvitations}
    methods: [GET]

accept_pending_invitation:
    pattern: /pending-invitation/{pendingInvitationId}/accept
    defaults: { _controller: MegasoftEntangleBundle:Tangle:acceptPendingInvitation}
    methods: [PUT]

reject_pending_invitation:
    pattern: /pending-invitation/{pendingInvitationId}/reject
    defaults: { _controller: MegasoftEntangleBundle:Tangle:rejectPendingInvitation}
    methods: [PUT]