megasoft_entangle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MegasoftEntangleBundle:Default:index }

check_membership:
    pattern: /tangle/{tangleId}/check-membership
    defaults: { _controller: MegasoftEntangleBundle:Tangle:checkMembership }
    methods: [POST]

invite:
    pattern: /tangle/{tangleId}/invite
    defaults: { _controller: MegasoftEntangleBundle:Tangle:invite }
    methods: [POST]


login:
    pattern:  /login
    defaults: { _controller: MegasoftEntangleBundle:User:login}
    methods: [POST]
    
    
    pattern:  /whoami
    defaults: { _controller: MegasoftEntangleBundle:User:whoAmI}
    methods: [GET]