# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do | config |
  # Use our base ubuntu box
  config.vm.box = "ubuntu-precise"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Forward port 8080 on the host to port 80 on the VM
  config.vm.forward_port 80, 9001
  config.vm.network :hostonly, "10.11.12.13", :netmask => "255.255.0.0"

  # Install the neccessary packages and update the VM
  config.vm.provision :shell, :path => "conf/bootstrap.sh"

   # Set the ownership of our public folder to www-data
  config.vm.share_folder("public", "/vagrant/public", "./public", :owner => "www-data", :group => "www-data")
  config.vm.customize ["modifyvm", :id, "--memory", "512"]
end
