megasoft_entangle:
    resource: "@MegasoftEntangleBundle/Resources/config/routing.yml"
    prefix:   /

notify:
    path:      /request/{offerid}
    defaults:  { _controller: MegasoftEntangleBundle:Offer:notify }
    methods: [POST]

profile:
    pattern: tangle/{tangleId}/user/{userId}/profile
    defaults: { _controller: MegasoftEntangleBundle:User:profile }
    methods: [GET]

