megasoft_entangle:
    resource: "@MegasoftEntangleBundle/Resources/config/routing.yml"
    prefix:   /
    
update:
    path:      /request/{offerid}
    defaults:  { _controller: MegasoftEntangleBundle:Offer:update }
    methods: [POST]
    

profile:
    pattern: tangle/{tangleId}/user/{userId}/profile
    defaults: { _controller: MegasoftEntangleBundle:User:profile }
    methods: [GET]