megasoft_entangle:
    resource: "@MegasoftEntangleBundle/Resources/config/routing.yml"
    prefix:   /
    
update:
    path:      /update/{offerid}
    defaults:  { _controller: MegasoftEntangleBundle:Offer:update }
    methods: [POST]
    
    
search:
    path:      /search/{offerid}
    defaults:  { _controller: MegasoftEntangleBundle:Offer:search }

profile:
    pattern: tangle/{tangleId}/user/{userId}/profile
    defaults: { _controller: MegasoftEntangleBundle:User:profile }
    methods: [GET]