megasoft_entangle:
    resource: "@MegasoftEntangleBundle/Resources/config/routing.yml"
    prefix:   /

<<<<<<< HEAD
notify:
    path:      /notify/{offerid}
    defaults:  { _controller: MegasoftEntangleBundle:Tangle:notify }
    methods: [POST]
=======
profile:
    pattern: tangle/{tangleId}/user/{userId}/profile
    defaults: { _controller: MegasoftEntangleBundle:User:profile }
    methods: [GET]
>>>>>>> 6ad054301d90f9bfda907c33e2150ae6c6ad173a
